name: GAPic
version: "0.1-beta"
license: "GPL-2.0-or-later"
date: 2023-10-20
description: |
    GAP image creator, for visualizing structures

authors:
    - name: Alice Niemeyer
      url: http://www.math.rwth-aachen.de/~Alice.Niemeyer/
    - name: Markus Baumeister
      url: https://markusbaumeister.github.io/
    - name: Reymond Akpanya
      url: mailto:akpanya@art.rwth-aachen.de
    - name: Tom Görtzen
      url: mailto:goertzen@art.rwth-aachen.de
    - name: Meike Weiß
      url: mailto:meike.weiss@rwth-aachen.de
    - name: Lukas Schnelle
      url: https://lukasschnelle.de

maintainers:
    - name: Alice Niemeyer
      url: http://www.math.rwth-aachen.de/~Alice.Niemeyer/
    - name: Reymond Akpanya
      url: mailto:akpanya@art.rwth-aachen.de
    - name: Tom Görtzen
      url: mailto:goertzen@art.rwth-aachen.de
    - name: Meike Weiß
      url: mailto:meike.weiss@rwth-aachen.de
    - name: Lukas Schnelle
      url: https://lukasschnelle.de

GAP: ">= 4.11"

www: https://github.com/GAP-ART-RWTH/GAPic
readme: README.md
packageinfo: https://github.com/GAP-ART-RWTH/GAPic/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/GAP-ART-RWTH/GAPic/releases/download/v0.1-beta/GAPic-0.1-beta.tar.gz

abstract: |

status: dev
doc-html: doc/html-version/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NBAGWS23</span>]   <b class='BibAuthor'>Niemeyer, A., Baumeister, M., Akpanya, R., Görtzen, T., Weiß, M. and Schnelle, L.</b>,
     <i class='BibTitle'>GAPic, GAP image creator, for visualizing structures,
             Version 0.1-beta</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/GAP-ART-RWTH/GAPic">https://github.com/GAP-ART-RWTH/GAPic</a></span>.
    </p>
    

bibtex: |
    @misc{ GAPic0.1-beta,
      author =           {Niemeyer,  A.  and  Baumeister, M. and Akpanya, R. and
                          G{\"o}rtzen, T. and Wei{\ss}, M. and Schnelle, L.},
      title =            {{GAPic},    GAP   image   creator,   for   visualizing
                          structures, {V}ersion 0.1-beta},
      month =            {Oct},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href          {https://github.com/GAP-ART-RWTH/GAPic}
                          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{GAP-ART-RWTH/}\discretionary
                          {}{}{}\texttt{GAPic}}},
      printedkey =       {NBAGWS23}
    }

